exclude_paths:
- jobs/awslogs-xenial/templates/helpers/
- jobs/awslogs-xenial/templates/bin/monit_debugger
- jobs/awslogs-xenial/templates/bin/ctl
- jobs/awslogs-xenial/templates/bin/scanner-ctl
plugins:
  shellcheck:
    enabled: true
